In [1]:
import numpy as np
import theano
import theano.tensor as T

In [3]:
X, Y, Z = T.scalar('x'), T.scalar('y'), T.scalar('z')

In [6]:
import theano.ifelse
theano.ifelse.ifelse(X > 2, Y, Z).eval({X: 3, Y: 4, Z: 5})

array(4.0, dtype=float32)

In [7]:
M = T.matrix('M')

In [8]:
M[1, :].eval({M: [[1, 2], [3, 4]]})

array([ 3.,  4.], dtype=float32)

In [9]:
M[1, :] = 7

TypeError: 'TensorVariable' object does not support item assignment

In [11]:
M_new = T.set_subtensor(M[1, :], 7)
M_new.eval({M: [[1, 2], [3, 4]]})

array([[ 1.,  2.],
       [ 7.,  7.]], dtype=float32)

In [15]:
X, Y, Z = T.vector('x'), T.vector('y'), T.vector('z')
XYZ = T.stack([X, Y, Z]).eval({
        X: [1,2],
        Y: [3,4],
        Z: [5,6]
    })
print(XYZ)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [18]:
X_reshaped = T.reshape(X, (3, -1)).eval({
            X: [1,2,3,4,5,6,7,8,9]
        })
print(X_reshaped)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [22]:
A, B = T.tensor3('A'), T.tensor3('B')
AB = T.tensordot(A, B, axes=[1, 2]).eval({
        A: np.random.random((3, 2, 4)).astype(np.float32),
        B: np.random.random((7, 5, 2)).astype(np.float32)
    })
print(AB.shape)

(3, 4, 7, 5)
